// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const changePassword = `-- name: ChangePassword :execrows
UPDATE accounts SET password_hash = $3, version = version + 1, updated_at = now()
WHERE id = $1 AND user_id = $2 AND provider_id = 'credential' AND revoked_at IS NULL
`

type ChangePasswordParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	PasswordHash *string
}

func (q *Queries) ChangePassword(ctx context.Context, arg ChangePasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, changePassword, arg.ID, arg.UserID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts(user_id, provider_id, provider_account_id, provider_namespace, password_hash)
VALUES ($1, $2, $3, $4, $5) RETURNING id, user_id, provider_id, provider_account_id, provider_namespace, password_hash, version, created_at, updated_at, last_used_at, revoked_at
`

type CreateAccountParams struct {
	UserID            uuid.UUID
	ProviderID        string
	ProviderAccountID string
	ProviderNamespace string
	PasswordHash      *string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.ProviderID,
		arg.ProviderAccountID,
		arg.ProviderNamespace,
		arg.PasswordHash,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderID,
		&i.ProviderAccountID,
		&i.ProviderNamespace,
		&i.PasswordHash,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const findProviderAccount = `-- name: FindProviderAccount :one
SELECT id, user_id, provider_id, provider_account_id, provider_namespace, password_hash, version, created_at, updated_at, last_used_at, revoked_at FROM accounts WHERE provider_namespace = $1 AND provider_account_id = $2 AND revoked_at IS NULL
`

type FindProviderAccountParams struct {
	ProviderNamespace string
	ProviderAccountID string
}

func (q *Queries) FindProviderAccount(ctx context.Context, arg FindProviderAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, findProviderAccount, arg.ProviderNamespace, arg.ProviderAccountID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderID,
		&i.ProviderAccountID,
		&i.ProviderNamespace,
		&i.PasswordHash,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, provider_id, provider_account_id, provider_namespace, password_hash, version, created_at, updated_at, last_used_at, revoked_at FROM accounts WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type GetAccountParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderID,
		&i.ProviderAccountID,
		&i.ProviderNamespace,
		&i.PasswordHash,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPasswordAccount = `-- name: GetPasswordAccount :one
SELECT id, user_id, provider_id, provider_account_id, provider_namespace, password_hash, version, created_at, updated_at, last_used_at, revoked_at FROM accounts WHERE user_id = $1 AND provider_id = 'credential' AND revoked_at IS NULL
`

func (q *Queries) GetPasswordAccount(ctx context.Context, userID uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getPasswordAccount, userID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderID,
		&i.ProviderAccountID,
		&i.ProviderNamespace,
		&i.PasswordHash,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, user_id, provider_id, provider_account_id, provider_namespace, password_hash, version, created_at, updated_at, last_used_at, revoked_at FROM accounts WHERE user_id = $1 AND revoked_at IS NULL ORDER BY created_at, id
`

func (q *Queries) ListAccounts(ctx context.Context, userID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProviderID,
			&i.ProviderAccountID,
			&i.ProviderNamespace,
			&i.PasswordHash,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccount = `-- name: RevokeAccount :execrows
UPDATE accounts SET revoked_at = now(), version = version + 1, updated_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeAccountParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RevokeAccount(ctx context.Context, arg RevokeAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAccount, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAccount = `-- name: TouchAccount :exec
UPDATE accounts SET last_used_at = now() WHERE id = $1 AND user_id = $2
`

type TouchAccountParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) TouchAccount(ctx context.Context, arg TouchAccountParams) error {
	_, err := q.db.Exec(ctx, touchAccount, arg.ID, arg.UserID)
	return err
}

const upgradePasswordHash = `-- name: UpgradePasswordHash :exec
UPDATE accounts SET password_hash = $3, updated_at = now()
WHERE id = $1 AND user_id = $2 AND password_hash = $4 AND revoked_at IS NULL
`

type UpgradePasswordHashParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	PasswordHash   *string
	PasswordHash_2 *string
}

func (q *Queries) UpgradePasswordHash(ctx context.Context, arg UpgradePasswordHashParams) error {
	_, err := q.db.Exec(ctx, upgradePasswordHash,
		arg.ID,
		arg.UserID,
		arg.PasswordHash,
		arg.PasswordHash_2,
	)
	return err
}
