// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const appendAudit = `-- name: AppendAudit :exec
INSERT INTO audit_events(action, outcome, actor_type, actor_id, resource_type, resource_id, scope_subject, session_id, request_id, reason_code, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type AppendAuditParams struct {
	Action       string
	Outcome      string
	ActorType    string
	ActorID      *string
	ResourceType string
	ResourceID   *string
	ScopeSubject *string
	SessionID    *uuid.UUID
	RequestID    *string
	ReasonCode   *string
	Metadata     []byte
}

func (q *Queries) AppendAudit(ctx context.Context, arg AppendAuditParams) error {
	_, err := q.db.Exec(ctx, appendAudit,
		arg.Action,
		arg.Outcome,
		arg.ActorType,
		arg.ActorID,
		arg.ResourceType,
		arg.ResourceID,
		arg.ScopeSubject,
		arg.SessionID,
		arg.RequestID,
		arg.ReasonCode,
		arg.Metadata,
	)
	return err
}
