// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_verifications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const consumeVerification = `-- name: ConsumeVerification :execrows
UPDATE auth_verifications SET consumed_at = now()
WHERE id = $1 AND user_id = $2 AND consumed_at IS NULL AND expires_at > now()
`

type ConsumeVerificationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ConsumeVerification(ctx context.Context, arg ConsumeVerificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeVerification, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createVerification = `-- name: CreateVerification :one
INSERT INTO auth_verifications(user_id, purpose, token_hash, email, auth_version, session_id, reauthentication_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now() + $8::bigint * interval '1 second') RETURNING id, user_id, purpose, token_hash, email, auth_version, session_id, reauthentication_id, created_at, expires_at, consumed_at
`

type CreateVerificationParams struct {
	UserID             uuid.UUID
	Purpose            string
	TokenHash          []byte
	Email              string
	AuthVersion        int64
	SessionID          *uuid.UUID
	ReauthenticationID *uuid.UUID
	TtlSeconds         int64
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) (AuthVerification, error) {
	row := q.db.QueryRow(ctx, createVerification,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.Email,
		arg.AuthVersion,
		arg.SessionID,
		arg.ReauthenticationID,
		arg.TtlSeconds,
	)
	var i AuthVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.Email,
		&i.AuthVersion,
		&i.SessionID,
		&i.ReauthenticationID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const findVerification = `-- name: FindVerification :one
SELECT id, user_id, purpose, token_hash, email, auth_version, session_id, reauthentication_id, created_at, expires_at, consumed_at FROM auth_verifications WHERE token_hash = $1 AND consumed_at IS NULL AND expires_at > now()
`

func (q *Queries) FindVerification(ctx context.Context, tokenHash []byte) (AuthVerification, error) {
	row := q.db.QueryRow(ctx, findVerification, tokenHash)
	var i AuthVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.Email,
		&i.AuthVersion,
		&i.SessionID,
		&i.ReauthenticationID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}
