// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_flows.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimAuthorization = `-- name: ClaimAuthorization :execrows
UPDATE auth_flows SET status = 'claimed', claimed_by = $2
WHERE id = $1 AND status = 'authorized' AND expires_at > now()
`

type ClaimAuthorizationParams struct {
	ID        uuid.UUID
	ClaimedBy *uuid.UUID
}

func (q *Queries) ClaimAuthorization(ctx context.Context, arg ClaimAuthorizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimAuthorization, arg.ID, arg.ClaimedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimFlow = `-- name: ClaimFlow :execrows
UPDATE auth_flows SET status = 'processing' WHERE id = $1 AND status = 'pending' AND expires_at > now()
`

func (q *Queries) ClaimFlow(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, claimFlow, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createFlow = `-- name: CreateFlow :one
INSERT INTO auth_flows(id, purpose, token_hash, provider_id, config_version, user_id, session_id, auth_version, account_id, account_version,
 operation, target, reauthentication_id, state_hash, protocol_state, status, authenticated_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, now() + interval '5 minutes') RETURNING id, purpose, token_hash, provider_id, config_version, user_id, session_id, auth_version, account_id, account_version, operation, target, reauthentication_id, claimed_by, state_hash, protocol_state, verified_namespace, verified_subject, verified_name, authenticated_at, status, created_at, expires_at
`

type CreateFlowParams struct {
	ID                 uuid.UUID
	Purpose            string
	TokenHash          []byte
	ProviderID         string
	ConfigVersion      string
	UserID             *uuid.UUID
	SessionID          *uuid.UUID
	AuthVersion        int64
	AccountID          *uuid.UUID
	AccountVersion     int64
	Operation          string
	Target             string
	ReauthenticationID *uuid.UUID
	StateHash          []byte
	ProtocolState      []byte
	Status             string
	AuthenticatedAt    *time.Time
}

func (q *Queries) CreateFlow(ctx context.Context, arg CreateFlowParams) (AuthFlow, error) {
	row := q.db.QueryRow(ctx, createFlow,
		arg.ID,
		arg.Purpose,
		arg.TokenHash,
		arg.ProviderID,
		arg.ConfigVersion,
		arg.UserID,
		arg.SessionID,
		arg.AuthVersion,
		arg.AccountID,
		arg.AccountVersion,
		arg.Operation,
		arg.Target,
		arg.ReauthenticationID,
		arg.StateHash,
		arg.ProtocolState,
		arg.Status,
		arg.AuthenticatedAt,
	)
	var i AuthFlow
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.TokenHash,
		&i.ProviderID,
		&i.ConfigVersion,
		&i.UserID,
		&i.SessionID,
		&i.AuthVersion,
		&i.AccountID,
		&i.AccountVersion,
		&i.Operation,
		&i.Target,
		&i.ReauthenticationID,
		&i.ClaimedBy,
		&i.StateHash,
		&i.ProtocolState,
		&i.VerifiedNamespace,
		&i.VerifiedSubject,
		&i.VerifiedName,
		&i.AuthenticatedAt,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const failFlow = `-- name: FailFlow :exec
UPDATE auth_flows SET status = 'failed', protocol_state = NULL WHERE id = $1 AND status IN ('pending', 'processing')
`

func (q *Queries) FailFlow(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, failFlow, id)
	return err
}

const findFlow = `-- name: FindFlow :one
SELECT id, purpose, token_hash, provider_id, config_version, user_id, session_id, auth_version, account_id, account_version, operation, target, reauthentication_id, claimed_by, state_hash, protocol_state, verified_namespace, verified_subject, verified_name, authenticated_at, status, created_at, expires_at FROM auth_flows WHERE token_hash = $1 AND expires_at > now()
`

func (q *Queries) FindFlow(ctx context.Context, tokenHash []byte) (AuthFlow, error) {
	row := q.db.QueryRow(ctx, findFlow, tokenHash)
	var i AuthFlow
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.TokenHash,
		&i.ProviderID,
		&i.ConfigVersion,
		&i.UserID,
		&i.SessionID,
		&i.AuthVersion,
		&i.AccountID,
		&i.AccountVersion,
		&i.Operation,
		&i.Target,
		&i.ReauthenticationID,
		&i.ClaimedBy,
		&i.StateHash,
		&i.ProtocolState,
		&i.VerifiedNamespace,
		&i.VerifiedSubject,
		&i.VerifiedName,
		&i.AuthenticatedAt,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const finishFlow = `-- name: FinishFlow :execrows
UPDATE auth_flows SET status = 'consumed', protocol_state = NULL
WHERE id = $1 AND status = $2 AND expires_at > now()
`

type FinishFlowParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) FinishFlow(ctx context.Context, arg FinishFlowParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishFlow, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFlow = `-- name: GetFlow :one
SELECT id, purpose, token_hash, provider_id, config_version, user_id, session_id, auth_version, account_id, account_version, operation, target, reauthentication_id, claimed_by, state_hash, protocol_state, verified_namespace, verified_subject, verified_name, authenticated_at, status, created_at, expires_at FROM auth_flows WHERE id = $1 AND expires_at > now()
`

func (q *Queries) GetFlow(ctx context.Context, id uuid.UUID) (AuthFlow, error) {
	row := q.db.QueryRow(ctx, getFlow, id)
	var i AuthFlow
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.TokenHash,
		&i.ProviderID,
		&i.ConfigVersion,
		&i.UserID,
		&i.SessionID,
		&i.AuthVersion,
		&i.AccountID,
		&i.AccountVersion,
		&i.Operation,
		&i.Target,
		&i.ReauthenticationID,
		&i.ClaimedBy,
		&i.StateHash,
		&i.ProtocolState,
		&i.VerifiedNamespace,
		&i.VerifiedSubject,
		&i.VerifiedName,
		&i.AuthenticatedAt,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const verifyFlow = `-- name: VerifyFlow :execrows
UPDATE auth_flows SET status = $2, verified_namespace = $3, verified_subject = $4, verified_name = $5,
 authenticated_at = $6, protocol_state = NULL
WHERE id = $1 AND status = 'processing' AND expires_at > now()
`

type VerifyFlowParams struct {
	ID                uuid.UUID
	Status            string
	VerifiedNamespace string
	VerifiedSubject   string
	VerifiedName      string
	AuthenticatedAt   *time.Time
}

func (q *Queries) VerifyFlow(ctx context.Context, arg VerifyFlowParams) (int64, error) {
	result, err := q.db.Exec(ctx, verifyFlow,
		arg.ID,
		arg.Status,
		arg.VerifiedNamespace,
		arg.VerifiedSubject,
		arg.VerifiedName,
		arg.AuthenticatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
