// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mail_outbox.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimMail = `-- name: ClaimMail :one
WITH candidate AS (
    SELECT id FROM mail_outbox
    WHERE ((status = 'pending' AND available_at <= now()) OR (status = 'processing' AND leased_until <= now()))
      AND expires_at > now() AND attempts < $3::integer
    ORDER BY available_at, created_at
    FOR UPDATE SKIP LOCKED LIMIT 1
)
UPDATE mail_outbox SET status = 'processing', attempts = attempts + 1,
    lease_id = $1, leased_until = now() + $2::bigint * interval '1 second'
WHERE id = (SELECT id FROM candidate)
RETURNING id, kind, recipient, subject, body, status, attempts, available_at, expires_at, lease_id, leased_until, last_error, created_at, completed_at
`

type ClaimMailParams struct {
	LeaseID      *uuid.UUID
	LeaseSeconds int64
	MaxAttempts  int32
}

func (q *Queries) ClaimMail(ctx context.Context, arg ClaimMailParams) (MailOutbox, error) {
	row := q.db.QueryRow(ctx, claimMail, arg.LeaseID, arg.LeaseSeconds, arg.MaxAttempts)
	var i MailOutbox
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Recipient,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.ExpiresAt,
		&i.LeaseID,
		&i.LeasedUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeMail = `-- name: CompleteMail :execrows
UPDATE mail_outbox SET status = 'sent', recipient = '', subject = '', body = '',
    lease_id = NULL, leased_until = NULL, last_error = NULL, completed_at = now()
WHERE id = $1 AND lease_id = $2 AND status = 'processing' AND leased_until > now()
`

type CompleteMailParams struct {
	ID      uuid.UUID
	LeaseID *uuid.UUID
}

func (q *Queries) CompleteMail(ctx context.Context, arg CompleteMailParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeMail, arg.ID, arg.LeaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueMail = `-- name: EnqueueMail :exec
INSERT INTO mail_outbox(id, kind, recipient, subject, body, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type EnqueueMailParams struct {
	ID        uuid.UUID
	Kind      string
	Recipient string
	Subject   string
	Body      string
	ExpiresAt time.Time
}

func (q *Queries) EnqueueMail(ctx context.Context, arg EnqueueMailParams) error {
	_, err := q.db.Exec(ctx, enqueueMail,
		arg.ID,
		arg.Kind,
		arg.Recipient,
		arg.Subject,
		arg.Body,
		arg.ExpiresAt,
	)
	return err
}

const expireMail = `-- name: ExpireMail :exec
WITH expired AS (
    SELECT id FROM mail_outbox
    WHERE (status = 'pending' OR (status = 'processing' AND leased_until <= now()))
      AND (expires_at <= now() OR attempts >= $1::integer)
    ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT $2::integer
)
UPDATE mail_outbox SET status = 'failed', recipient = '', subject = '', body = '',
    lease_id = NULL, leased_until = NULL, completed_at = now(), last_error = 'expired_or_exhausted'
WHERE id IN (SELECT id FROM expired)
`

type ExpireMailParams struct {
	MaxAttempts int32
	BatchSize   int32
}

func (q *Queries) ExpireMail(ctx context.Context, arg ExpireMailParams) error {
	_, err := q.db.Exec(ctx, expireMail, arg.MaxAttempts, arg.BatchSize)
	return err
}

const retryMail = `-- name: RetryMail :execrows
UPDATE mail_outbox SET status = CASE WHEN attempts >= $3::integer OR expires_at <= now() THEN 'failed' ELSE 'pending' END,
    recipient = CASE WHEN attempts >= $3::integer OR expires_at <= now() THEN '' ELSE recipient END,
    subject = CASE WHEN attempts >= $3::integer OR expires_at <= now() THEN '' ELSE subject END,
    body = CASE WHEN attempts >= $3::integer OR expires_at <= now() THEN '' ELSE body END,
    completed_at = CASE WHEN attempts >= $3::integer OR expires_at <= now() THEN now() ELSE NULL END,
    available_at = now() + $4::bigint * interval '1 second',
    lease_id = NULL, leased_until = NULL, last_error = 'sender_unavailable'
WHERE id = $1 AND lease_id = $2 AND status = 'processing' AND leased_until > now()
`

type RetryMailParams struct {
	ID           uuid.UUID
	LeaseID      *uuid.UUID
	MaxAttempts  int32
	DelaySeconds int64
}

func (q *Queries) RetryMail(ctx context.Context, arg RetryMailParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryMail,
		arg.ID,
		arg.LeaseID,
		arg.MaxAttempts,
		arg.DelaySeconds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
