// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions(id, user_id, token_hash, auth_method, auth_source_id, auth_version, idle_expires_at, absolute_expires_at)
VALUES ($1, $2, $3, $4, $5, $6, now() + $7::bigint * interval '1 second', now() + $8::bigint * interval '1 second') RETURNING id, user_id, token_hash, auth_method, auth_source_id, authenticated_at, auth_version, created_at, last_seen_at, idle_expires_at, absolute_expires_at, revoked_at
`

type CreateSessionParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	TokenHash    []byte
	AuthMethod   string
	AuthSourceID uuid.UUID
	AuthVersion  int64
	IdleSeconds  int64
	MaxSeconds   int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.AuthMethod,
		arg.AuthSourceID,
		arg.AuthVersion,
		arg.IdleSeconds,
		arg.MaxSeconds,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.AuthMethod,
		&i.AuthSourceID,
		&i.AuthenticatedAt,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const findSession = `-- name: FindSession :one
SELECT s.id, s.user_id, s.token_hash, s.auth_method, s.auth_source_id, s.authenticated_at, s.auth_version, s.created_at, s.last_seen_at, s.idle_expires_at, s.absolute_expires_at, s.revoked_at FROM user_sessions s JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.revoked_at IS NULL AND s.idle_expires_at > now()
 AND s.absolute_expires_at > now() AND u.status = 'active' AND u.auth_version = s.auth_version
`

func (q *Queries) FindSession(ctx context.Context, tokenHash []byte) (UserSession, error) {
	row := q.db.QueryRow(ctx, findSession, tokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.AuthMethod,
		&i.AuthSourceID,
		&i.AuthenticatedAt,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getValidSession = `-- name: GetValidSession :one
SELECT s.id, s.user_id, s.token_hash, s.auth_method, s.auth_source_id, s.authenticated_at, s.auth_version, s.created_at, s.last_seen_at, s.idle_expires_at, s.absolute_expires_at, s.revoked_at FROM user_sessions s JOIN users u ON u.id = s.user_id
WHERE s.id = $1 AND s.user_id = $2 AND s.revoked_at IS NULL AND s.idle_expires_at > now()
 AND s.absolute_expires_at > now() AND u.status = 'active' AND u.auth_version = s.auth_version
`

type GetValidSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetValidSession(ctx context.Context, arg GetValidSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, getValidSession, arg.ID, arg.UserID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.AuthMethod,
		&i.AuthSourceID,
		&i.AuthenticatedAt,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT s.id, s.user_id, s.token_hash, s.auth_method, s.auth_source_id, s.authenticated_at, s.auth_version, s.created_at, s.last_seen_at, s.idle_expires_at, s.absolute_expires_at, s.revoked_at FROM user_sessions s JOIN users u ON u.id = s.user_id WHERE s.user_id = $1 AND s.revoked_at IS NULL
 AND s.idle_expires_at > now() AND s.absolute_expires_at > now() AND s.auth_version = u.auth_version
ORDER BY s.created_at DESC, s.id DESC LIMIT $2 OFFSET $3
`

type ListSessionsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, listSessions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSession{}
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.AuthMethod,
			&i.AuthSourceID,
			&i.AuthenticatedAt,
			&i.AuthVersion,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.IdleExpiresAt,
			&i.AbsoluteExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE user_sessions SET revoked_at = COALESCE(revoked_at, now()) WHERE id = $1 AND user_id = $2
`

type RevokeSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE user_sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE user_sessions s SET last_seen_at = now(), idle_expires_at = LEAST(s.absolute_expires_at, now() + $1::bigint * interval '1 second')
FROM users u WHERE s.id = $2 AND s.user_id = $3 AND u.id = s.user_id
 AND s.last_seen_at <= now() - $4::bigint * interval '1 millisecond' AND s.revoked_at IS NULL AND s.idle_expires_at > now()
 AND s.absolute_expires_at > now() AND u.status = 'active' AND u.auth_version = s.auth_version
`

type TouchSessionParams struct {
	IdleSeconds         int64
	ID                  uuid.UUID
	UserID              uuid.UUID
	RenewalMilliseconds int64
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession,
		arg.IdleSeconds,
		arg.ID,
		arg.UserID,
		arg.RenewalMilliseconds,
	)
	return err
}
