// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const activateUser = `-- name: ActivateUser :one
UPDATE users SET status = 'active', email_verified_at = now(), recovery_enabled = true, updated_at = now()
WHERE id = $1 AND status = 'pending' RETURNING id, display_name, email, email_normalized, email_verified_at, recovery_enabled, status, role, auth_version, created_at, updated_at
`

func (q *Queries) ActivateUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, activateUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerifiedAt,
		&i.RecoveryEnabled,
		&i.Status,
		&i.Role,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const bumpUserVersion = `-- name: BumpUserVersion :exec
UPDATE users SET auth_version = auth_version + 1, updated_at = now() WHERE id = $1
`

func (q *Queries) BumpUserVersion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, bumpUserVersion, id)
	return err
}

const createFederatedUser = `-- name: CreateFederatedUser :one
INSERT INTO users(display_name, status) VALUES ($1, 'active') RETURNING id, display_name, email, email_normalized, email_verified_at, recovery_enabled, status, role, auth_version, created_at, updated_at
`

func (q *Queries) CreateFederatedUser(ctx context.Context, displayName string) (User, error) {
	row := q.db.QueryRow(ctx, createFederatedUser, displayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerifiedAt,
		&i.RecoveryEnabled,
		&i.Status,
		&i.Role,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPendingUser = `-- name: CreatePendingUser :one
INSERT INTO users(email, email_normalized) VALUES ($1, $2)
ON CONFLICT (email_normalized) DO UPDATE SET email_normalized = users.email_normalized
RETURNING id, display_name, email, email_normalized, email_verified_at, recovery_enabled, status, role, auth_version, created_at, updated_at
`

type CreatePendingUserParams struct {
	Email           *string
	EmailNormalized *string
}

func (q *Queries) CreatePendingUser(ctx context.Context, arg CreatePendingUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createPendingUser, arg.Email, arg.EmailNormalized)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerifiedAt,
		&i.RecoveryEnabled,
		&i.Status,
		&i.Role,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, display_name, email, email_normalized, email_verified_at, recovery_enabled, status, role, auth_version, created_at, updated_at FROM users WHERE email_normalized = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, emailNormalized *string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, emailNormalized)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerifiedAt,
		&i.RecoveryEnabled,
		&i.Status,
		&i.Role,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.display_name, u.email, u.email_normalized, u.email_verified_at, u.recovery_enabled, u.status, u.role, u.auth_version, u.created_at, u.updated_at FROM users u JOIN user_sessions s ON s.user_id = u.id
WHERE u.id = $1 AND s.id = $2
 AND u.status = 'active' AND s.auth_version = u.auth_version
 AND s.revoked_at IS NULL AND s.idle_expires_at > now() AND s.absolute_expires_at > now()
`

type GetSessionUserParams struct {
	UserID    uuid.UUID
	SessionID uuid.UUID
}

func (q *Queries) GetSessionUser(ctx context.Context, arg GetSessionUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getSessionUser, arg.UserID, arg.SessionID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerifiedAt,
		&i.RecoveryEnabled,
		&i.Status,
		&i.Role,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, display_name, email, email_normalized, email_verified_at, recovery_enabled, status, role, auth_version, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerifiedAt,
		&i.RecoveryEnabled,
		&i.Status,
		&i.Role,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, display_name, email, email_normalized, email_verified_at, recovery_enabled, status, role, auth_version, created_at, updated_at FROM users ORDER BY created_at DESC, id DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Email,
			&i.EmailNormalized,
			&i.EmailVerifiedAt,
			&i.RecoveryEnabled,
			&i.Status,
			&i.Role,
			&i.AuthVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :one
SELECT id, display_name, email, email_normalized, email_verified_at, recovery_enabled, status, role, auth_version, created_at, updated_at FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerifiedAt,
		&i.RecoveryEnabled,
		&i.Status,
		&i.Role,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserStatus = `-- name: SetUserStatus :one
UPDATE users SET status = $2, auth_version = auth_version + 1, updated_at = now()
WHERE id = $1 RETURNING id, display_name, email, email_normalized, email_verified_at, recovery_enabled, status, role, auth_version, created_at, updated_at
`

type SetUserStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerifiedAt,
		&i.RecoveryEnabled,
		&i.Status,
		&i.Role,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users SET email = $2, email_normalized = $3, email_verified_at = now(), recovery_enabled = true,
 auth_version = auth_version + 1, updated_at = now() WHERE id = $1 AND status = 'active' RETURNING id, display_name, email, email_normalized, email_verified_at, recovery_enabled, status, role, auth_version, created_at, updated_at
`

type UpdateUserEmailParams struct {
	ID              uuid.UUID
	Email           *string
	EmailNormalized *string
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.ID, arg.Email, arg.EmailNormalized)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerifiedAt,
		&i.RecoveryEnabled,
		&i.Status,
		&i.Role,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users u SET display_name = $1, updated_at = now()
WHERE u.id = $2 AND u.status = 'active'
 AND EXISTS (
  SELECT 1 FROM user_sessions s
  WHERE s.id = $3 AND s.user_id = u.id
   AND s.revoked_at IS NULL AND s.idle_expires_at > now()
   AND s.absolute_expires_at > now() AND s.auth_version = u.auth_version
 )
RETURNING u.id, u.display_name, u.email, u.email_normalized, u.email_verified_at, u.recovery_enabled, u.status, u.role, u.auth_version, u.created_at, u.updated_at
`

type UpdateUserProfileParams struct {
	DisplayName string
	ID          uuid.UUID
	SessionID   uuid.UUID
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.DisplayName, arg.ID, arg.SessionID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerifiedAt,
		&i.RecoveryEnabled,
		&i.Status,
		&i.Role,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
