// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (owner_id, title, description, status)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, title, description, status, created_at, updated_at
`

type CreateTaskParams struct {
	OwnerID     string
	Title       string
	Description string
	Status      string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks WHERE id = $1 AND owner_id = $2
`

type DeleteTaskParams struct {
	ID      uuid.UUID
	OwnerID string
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTask = `-- name: GetTask :one
SELECT id, owner_id, title, description, status, created_at, updated_at FROM tasks WHERE id = $1 AND owner_id = $2
`

type GetTaskParams struct {
	ID      uuid.UUID
	OwnerID string
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.OwnerID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, owner_id, title, description, status, created_at, updated_at FROM tasks
WHERE owner_id = $1
  AND ($2::text = '' OR status = $2::text)
ORDER BY created_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListTasksParams struct {
	OwnerID      string
	StatusFilter string
	PageOffset   int32
	PageLimit    int32
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.OwnerID,
		arg.StatusFilter,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET title = $3, description = $4, status = $5, updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, title, description, status, created_at, updated_at
`

type UpdateTaskParams struct {
	ID          uuid.UUID
	OwnerID     string
	Title       string
	Description string
	Status      string
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
